# Generated by Django 5.2.12 on 2026-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_remove_autofield_use_bigautofield"),
        ("tags", "0003_rename_fk_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="logtag",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="logtag",
            constraint=models.UniqueConstraint(
                fields=("log", "tag"), name="uq_logtag_log_tag"
            ),
        ),
    ]
