# Generated by Django 5.2.12 on 2026-03-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
        ("tags", "0003_rename_fk_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="logs", through="tags.LogTag", to="tags.tag"
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
