# Generated by Django 5.2.12 on 2026-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_operation_tag_trigger"),
        ("tags", "0003_rename_fk_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="operation",
            name="idx_ops_tag",
        ),
        migrations.RemoveIndex(
            model_name="useroperation",
            name="idx_userop_op",
        ),
        migrations.RenameField(
            model_name="operation",
            old_name="tag_id",
            new_name="tag",
        ),
        migrations.RenameField(
            model_name="useroperation",
            old_name="operation_id",
            new_name="operation",
        ),
        migrations.AlterUniqueTogether(
            name="useroperation",
            unique_together={("username", "operation")},
        ),
        migrations.AlterField(
            model_name="operation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="useroperation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(fields=["tag"], name="idx_ops_tag"),
        ),
        migrations.AddIndex(
            model_name="useroperation",
            index=models.Index(fields=["operation"], name="idx_userop_op"),
        ),
    ]
