# Generated by Django 5.2.12 on 2026-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_rename_fk_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useroperation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="useroperation",
            constraint=models.UniqueConstraint(
                fields=("username", "operation"),
                name="uq_useroperation_username_operation",
            ),
        ),
    ]
