# Generated by Django 5.2.12 on 2026-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencefile",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="evidence/"),
        ),
        migrations.AlterField(
            model_name="evidencefile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
