"""Generate .env files with random secrets for the Overwatch platform.

NOTE (PoC): SSL/TLS-related variables (POSTGRES_SSL, REDIS_SSL,
REDIS_ENCRYPTION_KEY, LETSENCRYPT_*) have been removed for simplicity.
In production, re-add these and enable TLS on Redis, PostgreSQL, and nginx.
"""

import os
import secrets
import string
from pathlib import Path


def _random_hex(n_bytes: int) -> str:
    """Return a cryptographically-random hex string of *n_bytes* bytes."""
    return secrets.token_hex(n_bytes)


def _random_password(length: int = 24) -> str:
    """Return a random alphanumeric password."""
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _write_file(path: Path, content: str) -> None:
    """Write *content* to *path*, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    os.chmod(path, 0o600)


def write_env_files(base_dir: Path) -> None:
    """Generate and write all .env files for the Overwatch platform.

    *base_dir* is the ``overwatch/`` project directory (one level inside the repo
    root where ``compose.yaml`` now lives).

    Files created:
        <base_dir>/../.env             - repo-root compose env (variable substitution)
        <base_dir>/backend/.env        - backend service env
    """
    # compose.yaml lives one level above base_dir (at the repo root)
    compose_dir = base_dir.parent

    # --- Generate secrets ---
    django_secret_key = _random_hex(50)
    jwt_secret = _random_hex(32)

    admin_password = _random_password()
    user_password = _random_password()
    redis_password = _random_password()
    postgres_password = _random_password()

    # --- Root .env (consumed by compose.yaml for variable substitution) ---
    root_env = f"""\
# Auto-generated by generate_env - do not commit this file
POSTGRES_USER=overwatch
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=redteamlogger
REDIS_PASSWORD={redis_password}
"""
    _write_file(compose_dir / ".env", root_env)

    # --- Backend .env ---
    # REDIS_URL must embed the password so Django cache and Celery can connect.
    # NOTE (PoC): DJANGO_SETTINGS_MODULE uses development settings so
    # ALLOWED_HOSTS=* and CORS_ALLOW_ALL_ORIGINS=True — not safe for production.
    backend_env = f"""\
# Auto-generated by generate_env - do not commit this file
DJANGO_SETTINGS_MODULE=backend.settings.development
DJANGO_SECRET_KEY={django_secret_key}
POSTGRES_USER=overwatch
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=redteamlogger
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
REDIS_URL=redis://:{redis_password}@127.0.0.1:6379/0
JWT_SECRET={jwt_secret}
ADMIN_PASSWORD={admin_password}
USER_PASSWORD={user_password}
"""
    _write_file(base_dir / "backend" / ".env", backend_env)

    print(f"  Environment files written:")
    print(f"    {compose_dir / '.env'}")
    print(f"    {base_dir / 'backend' / '.env'}")
