"""Generate .env files with random secrets for the Clio platform."""

import os
import secrets
import string
from pathlib import Path


def _random_hex(n_bytes: int) -> str:
    """Return a cryptographically-random hex string of *n_bytes* bytes."""
    return secrets.token_hex(n_bytes)


def _random_password(length: int = 24) -> str:
    """Return a random alphanumeric password."""
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _write_file(path: Path, content: str) -> None:
    """Write *content* to *path*, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    os.chmod(path, 0o600)


def write_env_files(
    base_dir: Path,
    *,
    letsencrypt_cert_path: str = "",
    letsencrypt_key_path: str = "",
) -> None:
    """Generate and write all .env files for the Clio platform.

    Files created:
        <base_dir>/.env               - root compose env
        <base_dir>/backend/.env        - backend service env
        <base_dir>/relation_service/.env - relation-service env
    """
    # --- Generate secrets ---
    redis_encryption_key = _random_hex(32)
    jwt_secret = _random_hex(32)
    admin_secret = _random_hex(32)
    field_encryption_key = _random_hex(32)
    server_instance_id = _random_hex(16)

    admin_password = _random_password()
    user_password = _random_password()
    redis_password = _random_password()
    postgres_password = _random_password()

    # --- Root .env (consumed by docker-compose.yml) ---
    root_env = f"""\
# Auto-generated by generate_env - do not commit this file
POSTGRES_USER=clio
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=redteamlogger
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_SSL=true
REDIS_PASSWORD={redis_password}
REDIS_SSL=true
REDIS_ENCRYPTION_KEY={redis_encryption_key}
JWT_SECRET={jwt_secret}
ADMIN_PASSWORD={admin_password}
USER_PASSWORD={user_password}
ADMIN_SECRET={admin_secret}
FIELD_ENCRYPTION_KEY={field_encryption_key}
SERVER_INSTANCE_ID={server_instance_id}
PORT=3001
NODE_ENV=production
FRONTEND_URL=https://localhost
HOSTNAME=localhost
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=https://localhost:3000/api/auth/google/callback
LETSENCRYPT_CERT_PATH={letsencrypt_cert_path}
LETSENCRYPT_KEY_PATH={letsencrypt_key_path}
"""
    _write_file(base_dir / ".env", root_env)

    # --- Backend .env ---
    backend_env = f"""\
# Auto-generated by generate_env - do not commit this file
POSTGRES_USER=clio
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=redteamlogger
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_SSL=true
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD={redis_password}
REDIS_SSL=true
REDIS_ENCRYPTION_KEY={redis_encryption_key}
JWT_SECRET={jwt_secret}
ADMIN_PASSWORD={admin_password}
USER_PASSWORD={user_password}
ADMIN_SECRET={admin_secret}
FIELD_ENCRYPTION_KEY={field_encryption_key}
SERVER_INSTANCE_ID={server_instance_id}
PORT=3001
NODE_ENV=production
FRONTEND_URL=https://localhost
HOSTNAME=localhost
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=https://localhost:3000/api/auth/google/callback
LETSENCRYPT_CERT_PATH={letsencrypt_cert_path}
LETSENCRYPT_KEY_PATH={letsencrypt_key_path}
"""
    _write_file(base_dir / "backend" / ".env", backend_env)

    # --- Relation-service .env ---
    relation_env = f"""\
# Auto-generated by generate_env - do not commit this file
POSTGRES_USER=clio
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=redteamlogger
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_SSL=true
PORT=3002
NODE_ENV=production
JWT_SECRET={jwt_secret}
SERVER_INSTANCE_ID={server_instance_id}
"""
    _write_file(base_dir / "relation_service" / ".env", relation_env)

    print(f"  Environment files written:")
    print(f"    {base_dir / '.env'}")
    print(f"    {base_dir / 'backend' / '.env'}")
    print(f"    {base_dir / 'relation_service' / '.env'}")
