"""Generate .env files with random secrets for the Clio platform.

NOTE (PoC): SSL/TLS-related variables (POSTGRES_SSL, REDIS_SSL,
REDIS_ENCRYPTION_KEY, LETSENCRYPT_*) have been removed for simplicity.
In production, re-add these and enable TLS on Redis, PostgreSQL, and nginx.
"""

import os
import secrets
import string
from pathlib import Path


def _random_hex(n_bytes: int) -> str:
    """Return a cryptographically-random hex string of *n_bytes* bytes."""
    return secrets.token_hex(n_bytes)


def _random_password(length: int = 24) -> str:
    """Return a random alphanumeric password."""
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _write_file(path: Path, content: str) -> None:
    """Write *content* to *path*, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    os.chmod(path, 0o600)


def write_env_files(base_dir: Path) -> None:
    """Generate and write all .env files for the Clio platform.

    Files created:
        <base_dir>/.env               - root compose env (variable substitution)
        <base_dir>/backend/.env        - backend service env
        <base_dir>/relation_service/.env - relation-service env
    """
    # --- Generate secrets ---
    jwt_secret = _random_hex(32)
    admin_secret = _random_hex(32)
    field_encryption_key = _random_hex(32)
    server_instance_id = _random_hex(16)

    admin_password = _random_password()
    user_password = _random_password()
    redis_password = _random_password()
    postgres_password = _random_password()

    # --- Root .env (consumed by compose.yaml for variable substitution) ---
    root_env = f"""\
# Auto-generated by generate_env - do not commit this file
POSTGRES_USER=clio
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=redteamlogger
REDIS_PASSWORD={redis_password}
"""
    _write_file(base_dir / ".env", root_env)

    # --- Backend .env ---
    # REDIS_URL must embed the password so Django cache and Celery can connect.
    # NOTE (PoC): DJANGO_SETTINGS_MODULE uses development settings so
    # ALLOWED_HOSTS=* and CORS_ALLOW_ALL_ORIGINS=True — not safe for production.
    backend_env = f"""\
# Auto-generated by generate_env - do not commit this file
DJANGO_SETTINGS_MODULE=backend.settings.development
POSTGRES_USER=clio
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=redteamlogger
POSTGRES_HOST=db
POSTGRES_PORT=5432
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD={redis_password}
REDIS_URL=redis://:{redis_password}@redis:6379/0
JWT_SECRET={jwt_secret}
ADMIN_PASSWORD={admin_password}
USER_PASSWORD={user_password}
ADMIN_SECRET={admin_secret}
FIELD_ENCRYPTION_KEY={field_encryption_key}
SERVER_INSTANCE_ID={server_instance_id}
PORT=3001
FRONTEND_URL=http://localhost:3000
HOSTNAME=localhost
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=http://localhost:3000/api/auth/google/callback
"""
    _write_file(base_dir / "backend" / ".env", backend_env)

    # --- Relation-service .env ---
    relation_env = f"""\
# Auto-generated by generate_env - do not commit this file
POSTGRES_USER=clio
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=redteamlogger
POSTGRES_HOST=db
POSTGRES_PORT=5432
PORT=3002
JWT_SECRET={jwt_secret}
SERVER_INSTANCE_ID={server_instance_id}
"""
    _write_file(base_dir / "relation_service" / ".env", relation_env)

    print(f"  Environment files written:")
    print(f"    {base_dir / '.env'}")
    print(f"    {base_dir / 'backend' / '.env'}")
    print(f"    {base_dir / 'relation_service' / '.env'}")
