# Generated by Django 5.2.12 on 2026-03-26 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_remove_autofield_use_bigautofield"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAIContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("complete", "complete"),
                            ("error", "error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("mitre_techniques", models.JSONField(default=list)),
                ("cves", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "log_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_context",
                        to="logs.log",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogAIContextSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_type", models.CharField(max_length=20)),
                ("record_id", models.CharField(max_length=100)),
                ("source_url", models.URLField(blank=True)),
                ("retrieved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="logs.logaicontext",
                    ),
                ),
            ],
        ),
    ]
