# Generated by Django 5.2.12 on 2026-03-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="relation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.UniqueConstraint(
                fields=("source_type", "source_value", "target_type", "target_value"),
                name="uq_relation_source_target",
            ),
        ),
    ]
