# Generated by Django 5.2.12 on 2026-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_seed_default_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logtag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
