# Generated by Django 5.2.12 on 2026-03-23 16:26

import api_keys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="permissions",
            field=models.JSONField(default=api_keys.models.default_permissions),
        ),
    ]
